error:
  whitelabel:
    enabled: false

amazon:
  associateId: habuma-20

logging:
  level:
    root: INFO

endpoints:
  jmx:
    domain: readinglist
    uniqueNames: true
  beans:
    sensitive: true

  health:
    enabled: true
    sensitive: false

management:
  context-path: /mgmt

  health:
    mongo:
      enabled: false